rvm:
  - 2.5.0
  - 2.5.8
  - 2.6.0
  - 2.6.6
  - 2.7.0
  - 2.7.2
  - ruby-head
  - jruby-head
notifications:
  recipients:
    - karl@kandrsoftware.com
branches:
  only:
    - master
    - develop
before_install:
  - sudo apt-get update
  - sudo apt-get -y install espeak
  # ensure that we are building/testing againt the newest depencency versions
bundler_args: --without development
script: bundle exec rspec
